### ISSUE TITLE
#include <ESP8266WebServer.h> can be replaced with #include <WebServer.h>

### ISSUE THREAD

**Issue by zombodotcom** [jasoncoon/esp32-fastled-webserver#10]
I just got it running with WebServer.h from espressif for the esp32 without changing anything in the code. Just

#include <ESP8266WebServer.h>
to #include <WebServer.h>

**Comment by piotrkochan** [comment]
You can make a pull request

**Comment by spattinson** [comment]
I can confirm that this works. the web page was not loading with #include <ESP8266WebServer.h> I copied the library from https://github.com/espressif/arduino-esp32 and change to #include <WebServer.h>

**Comment by DougBarry** [comment]
FYI this tip meant that the user interface presented over wifi on my esp32 kit worked properly, before it was missing the user controls other than the burger menu.
