### ISSUE TITLE
compilation failure due to trailing semicolon

### ISSUE THREAD

**Issue by marcmerlin** [jasoncoon/esp32-fastled-webserver#22]
--- a/patterns.h
+++ b/patterns.h
@@ -22,7 +22,7 @@
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
 
-#include "palettes.h";
+#include "palettes.h"
 #include "twinkleFox.h"

**Comment by jasoncoon** [comment]
Should be fixed now, thanks!
