### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by Intrinsically-Sublime** [jasoncoon/esp32-fastled-webserver#3]
In patterns.h you have
#include "twinkleFOX.h"
but it should be
#include "twinkleFox.h"
Your copy of esp32fs.jar is 43.2KB and doesn't work with Arduino IDE 1.8.1 but the on in Yves BAZINS repo https://github.com/hpwit/lib is only 7.42KB and does appear in the tools menu.

Thanks for all the hard work making this and the Esp8266 server it is much appreciated. I still haven't been able to get the esp32 version to serve the index page but I'm sure I'll get there.

**Comment by jasoncoon** [comment]
Fixed, thanks!  https://github.com/jasoncoon/esp32-fastled-webserver/commit/c6718bd4b5d7b815064de8785f65f12faca1ec76
