### ISSUE TITLE
Flicker

### ISSUE THREAD

**Issue by jasoncoon** [jasoncoon/esp32-fastled-webserver#8]
LEDs flicker slightly.

**Comment by jasoncoon** [comment]
Seems to be improved, if not completely resolved now: https://github.com/jasoncoon/esp32-fastled-webserver/commit/c6718bd4b5d7b815064de8785f65f12faca1ec76

**Comment by pikipupiba** [comment]
I'm still getting a flicker that starts after the first 20 leds and gets more common at the far end of the strip. I have installed a logic level converter and I tried hooking the far end of the strip to the power supply as well. Neither thing has really affected the flickering at all.

**Comment by jasoncoon** [comment]
Which level shifter are you using?  Are you using the latest changes mentioned above?

**Comment by pikipupiba** [comment]
https://www.amazon.com/gp/product/B073D4DJDC/ref=ppx_yo_dt_b_asin_title_o00_s02?ie=UTF8&psc=1

I am pretty sure I am using the latest version. I just downloaded it 2 weeks ago.

**Comment by jasoncoon** [comment]
There are very few level shifters that are known and tested to be able to handle the speed required for WS281X or SPI based (APA102, etc) RGB LEDs.  The one most used is the 74HCT245: 

More details: https://happyinmotion.com/?p=1247

**Comment by pikipupiba** [comment]
Ordering new ones now. Thank you for your help!

**Comment by pikipupiba** [comment]
Soooooo all that I needed to do was change the FASTLED_SHOW_CORE to 1 instead of 0 and there is no longer any flicker at all. I have no idea why this would be the case but props to u_Jem_Spencer for the fix! Maybe change this in your code?

https://www.reddit.com/r/FastLED/comments/aup7ia/getting_a_flicker_when_using_esp32_and_level/

**Comment by jordanadania** [comment]
pikipupiba's solution worked for me
